version: "3.9"
services:
  app:
    depends_on:
      - database
    build:
      context: .
      target: development
    ports:
      - "8080:80"
    networks:
      - local-dev-network
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "qwe123QWE"
    ports:
      - "1433:1433"
    networks:
      - local-dev-network
networks:
  local-dev-network:
    name: local-dev-network